service: alexa-skill-kiwiquakes

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-east-1
  memorySize: 256
  cfLogs: true
  profile: kiwiquakes
  environment:
    GOOGLE_API_KEY: ${file(config.json):GOOGLE_API_KEY}

functions:
  skill: # function name
    handler: src/index.handler # path to the alexa handler function: {path}/{filename}.{handler function}
    description: Alexa Skill for New Zealand Earthquakes
    events:
      - alexaSkill # function trigger. for alexa skills it 'alexaSkill'

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-webpack
