service: alexa-skill-kiwiquakes

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-east-1
  memorySize: 256
  cfLogs: true

functions:
  skill: # function name
    handler: src/index.handler # path to the alexa handler function: {path}/{filename}.{handler function}
    description: Alexa Skill for New Zealand Earthquakes
    events:
      - alexaSkill # function trigger. for alexa skills it 'alexaSkill'

plugins:
  - serverless-webpack
